### ISSUE TITLE
Migrate to new Text LinkAnnotation API

### ISSUE THREAD

**Issue by Calvin-LL** [Calvin-LL/AutoLinkText#1]
Keep track of the new API's progress here: https://issuetracker.google.com/issues/139312671

**Comment by Calvin-LL** [comment]
Looks like this will be released in Compose Foundation v1.7.0 which is currently in alpha. https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.7.0-alpha07

I'll update this library once v1.7.0 make it to compose multiplatform.

**Comment by NinoDLC** [comment]
Compose 1.7.5 is available

**Comment by Calvin-LL** [comment]
v2.0.0 is out
