### ISSUE TITLE
Modifier.combinedClickable is not working

### ISSUE THREAD

**Issue by ihor-monochkov-enverus** [Calvin-LL/AutoLinkText#2]
I used long press to copy text in Compose Text using next code:
```
Modifier.combinedClickable(
          onClick = {},
          onLongClick = {
              clipboardManager.setText(AnnotatedString("Text"))
          },
)
```

And it does not work when I migrated from Text to AutoLinkText.

**Comment by Calvin-LL** [comment]
Can you share the actual code where you're using `AutoLinkText`? I can't exactly tell how you're using it. And what's the behavior? Nothing in the clipboard after long click?

**Comment by ihor-monochkov-enverus** [comment]
Nothing in the clipboard. `onLongClick` callback is not fired at all. 
Usage:
```
AutoLinkText(
            modifier = Modifier.combinedClickable(
                onClick = {},
                onLongClick = {
                    Log.v("Test", "long click")
                },
            ),
            text = stringResource(id = descriptionRes),
            style = MaterialTheme.typography.bodyMedium,
        )
```

By the way, I investigated it and would say that seems it is not issue of your library, but ClickableText from Jetpack Compose does not support it. So I will close this issue as not actual.
