### ISSUE TITLE
[Feature Request] Make default text color configurable

### ISSUE THREAD

**Issue by matsumo0922** [Calvin-LL/AutoLinkText#3]
Now `AutoLinkText` has no argument to set the text color, so if you want to set the default text color, you must use TextStyle to do so.

However, this Style takes precedence over `TextRule.style`, so the color of links, etc. will be consistent. Could you prevent this and still set the default text color?

↓ Current workaround (not smart :( )

```Kotlin
AutoLinkText(
    text = description,
    style = MaterialTheme.typography.bodyMedium.copy(color = MaterialTheme.colorScheme.onSurfaceVariant),
    textRules = TextRuleDefaults.defaultList().map {
        it.copy(
            style = SpanStyle(
                color = MaterialTheme.colorScheme.primary,
                textDecoration = TextDecoration.Underline,
            )
        )
    },
)
```

**Comment by Calvin-LL** [comment]
I'll take a look at this next week. Meanwhile, if anyone else want this, feel free to open a PR.

**Comment by Calvin-LL** [comment]
This issue should be moot in v2.0.0
