### ISSUE TITLE
Linkify Addresses

### ISSUE THREAD

**Issue by Tgo1014** [Calvin-LL/AutoLinkText#4]
Would it be possible to add default text rules to automatically linkify addresses?

**Comment by Calvin-LL** [comment]
Unfortunately for Android, there is no built-in address detector. (See https://developer.android.com/reference/androidx/core/util/PatternsCompat) You can use your own though.

**Comment by Tgo1014** [comment]
Hello @Calvin-LL, actually there is. 

There was this deprecated flag: https://developer.android.com/reference/android/text/util/Linkify#MAP_ADDRESSES and how there's this https://developer.android.com/reference/android/view/textclassifier/TextClassifier#TYPE_ADDRESS which support addresses but also other things like flights, that could also be an option to be added.

Can you take a look and see if it's worth to reopen this issue? Thanks!

**Comment by Calvin-LL** [comment]
Oh I see, thanks for digging into it. I'll take a look when I have time next week.
